In [1]:
   import sys; print(sys.executable)

d:\DataCo Supply Chain Project\supply-chain-data-science\.venv\Scripts\python.exe

In [2]:
from pathlib import Path
import pandas as pd

In [3]:

ROOT = Path.cwd().parent          # notebook lives in notebooks/, so go up one level
RAW = ROOT / "data" / "raw"

orders = pd.read_csv(RAW / "DataCoSupplyChainDataset.csv", encoding="latin-1")
logs   = pd.read_csv(RAW / "tokenized_access_logs.csv")
desc   = pd.read_csv(RAW / "DescriptionDataCoSupplyChain.csv", encoding="latin-1")

for name, df in {"orders": orders, "logs": logs, "desc": desc}.items():
    print(f"{name:7} {df.shape}")

orders  (180519, 53)
logs    (469977, 8)
desc    (52, 2)

In [4]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  str
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  str
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  str
 9   Customer City                  180519 non-null  str
 10  Customer Country               180519 non-null  str
 11  Customer Email                 180519 non-null  str
 12  Customer Fname                 180519 non-null  str
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  str
 15  Customer Password              180519 non-null  str
 16  Customer Segment               180519 non-null  str
 17  Customer State                 180519 non-null  str
 18  Customer Street                180519 non-null  str
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  str
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  str
 25  Order City                     180519 non-null  str
 26  Order Country                  180519 non-null  str
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  str
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  str
 41  Order State                    180519 non-null  str
 42  Order Status                   180519 non-null  str
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  str
 48  Product Name                   180519 non-null  str
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  str
 52  Shipping Mode                  180519 non-null  str
dtypes: float64(15), int64(14), str(24)
memory usage: 128.3 MB

In [5]:
orders.isna().sum().sort_values(ascending=False).head(10)

Product Description              180519
Order Zipcode                    155679
Customer Lname                        8
Customer Zipcode                      3
Days for shipment (scheduled)         0
Sales per customer                    0
Benefit per order                     0
Delivery Status                       0
Late_delivery_risk                    0
Customer City                         0
dtype: int64

In [7]:
orders.nunique().sort_values()

Product Description                   0
Customer Password                     1
Product Status                        1
Customer Email                        1
Late_delivery_risk                    2
Customer Country                      2
Customer Segment                      3
Delivery Status                       4
Days for shipment (scheduled)         4
Shipping Mode                         4
Type                                  4
Market                                5
Order Item Quantity                   5
Days for shipping (real)              7
Order Status                          9
Department Id                        11
Department Name                      11
Order Item Discount Rate             18
Order Region                         23
Customer State                       46
Category Name                        50
Product Category Id                  51
Category Id                          51
Order Item Product Price             75
Product Price                        75
Product Image                       118
Product Card Id                     118
Product Name                        118
Order Item Cardprod Id              118
Order Item Profit Ratio             162
Order Country                       164
Sales                               193
Customer City                       563
Order Zipcode                       609
Customer Fname                      782
Customer Zipcode                    995
Order Item Discount                1017
Order State                        1089
Customer Lname                     1109
Order Item Total                   2927
Sales per customer                 2927
Order City                         3597
Longitude                          4487
Customer Street                    7458
Latitude                          11250
Customer Id                       20652
Order Customer Id                 20652
Benefit per order                 21998
Order Profit Per Order            21998
shipping date (DateOrders)        63701
order date (DateOrders)           65752
Order Id                          65752
Order Item Id                    180519
dtype: int64

In [8]:
orders.head(3).T

,0,1,2
Type,DEBIT,TRANSFER,CASH
Days for shipping (real),3,5,4
Days for shipment (scheduled),4,4,4
Benefit per order,91.25,-249.089996,-247.779999
Sales per customer,314.640015,311.359985,309.720001
Delivery Status,Advance shipping,Late delivery,Shipping on time
Late_delivery_risk,0,1,0
Category Id,73,73,73
Category Name,Sporting Goods,Sporting Goods,Sporting Goods
Customer City,Caguas,Caguas,San Jose
Customer Country,Puerto Rico,Puerto Rico,EE. UU.
Customer Email,XXXXXXXXX,XXXXXXXXX,XXXXXXXXX
Customer Fname,Cally,Irene,Gillian
Customer Id,20755,19492,19491
Customer Lname,Holloway,Luna,Maldonado
Customer Password,XXXXXXXXX,XXXXXXXXX,XXXXXXXXX
Customer Segment,Consumer,Consumer,Consumer
Customer State,PR,PR,CA
Customer Street,5365 Noble Nectar Island,2679 Rustic Loop,8510 Round Bear Gate
Customer Zipcode,725.0,725.0,95125.0
Department Id,2,2,2
Department Name,Fitness,Fitness,Fitness
Latitude,18.251453,18.279451,37.292233
Longitude,-66.037056,-66.037064,-121.881279
Market,Pacific Asia,Pacific Asia,Pacific Asia
Order City,Bekasi,Bikaner,Bikaner
Order Country,Indonesia,India,India
Order Customer Id,20755,19492,19491
order date (DateOrders),1/31/2018 22:56,1/13/2018 12:27,1/13/2018 12:06
Order Id,77202,75939,75938
Order Item Cardprod Id,1360,1360,1360
Order Item Discount,13.11,16.389999,18.030001
Order Item Discount Rate,0.04,0.05,0.06
Order Item Id,180517,179254,179253
Order Item Product Price,327.75,327.75,327.75
Order Item Profit Ratio,0.29,-0.8,-0.8
Order Item Quantity,1,1,1
Sales,327.75,327.75,327.75
Order Item Total,314.640015,311.359985,309.720001
Order Profit Per Order,91.25,-249.089996,-247.779999
Order Region,Southeast Asia,South Asia,South Asia
Order State,Java Occidental,Rajastán,Rajastán
Order Status,COMPLETE,PENDING,CLOSED
Order Zipcode,NaN,NaN,NaN
Product Card Id,1360,1360,1360
Product Category Id,73,73,73
Product Description,NaN,NaN,NaN
Product Image,http://images.acmesports.sports/Smart+watch,http://images.acmesports.sports/Smart+watch,http://images.acmesports.sports/Smart+watch
Product Name,Smart watch,Smart watch,Smart watch
Product Price,327.75,327.75,327.75
Product Status,0,0,0
shipping date (DateOrders),2/3/2018 22:56,1/18/2018 12:27,1/17/2018 12:06
Shipping Mode,Standard Class,Standard Class,Standard Class

In [9]:
pd.set_option("display.max_colwidth", None)
desc

,FIELDS,DESCRIPTION
0,Type,: Type of transaction made
1,Days for shipping (real),: Actual shipping days of the purchased product
2,Days for shipment (scheduled),: Days of scheduled delivery of the purchased product
3,Benefit per order,: Earnings per order placed
4,Sales per customer,: Total sales per customer made per customer
5,Delivery Status,": Delivery status of orders: Advance shipping , Late delivery , Shipping canceled , Shipping on time"
6,Late_delivery_risk,": Categorical variable that indicates if sending is late (1), it is not late (0)."
7,Category Id,: Product category code
8,Category Name,: Description of the product category
9,Customer City,: City where the customer made the purchase
10,Customer Country,: Country where the customer made the purchase
11,Customer Email,: Customer's email
12,Customer Fname,: Customer name
13,Customer Id,: Customer ID
14,Customer Lname,: Customer lastname
15,Customer Password,: Masked customer key
16,Customer Segment,": Types of Customers: Consumer , Corporate , Home Office"
17,Customer State,: State to which the store where the purchase is registered belongs
18,Customer Street,: Street to which the store where the purchase is registered belongs
19,Customer Zipcode,: Customer Zipcode
20,Department Id,: Department code of store
21,Department Name,: Department name of store
22,Latitude,: Latitude corresponding to location of store
23,Longitude,: Longitude corresponding to location of store
24,Market,": Market to where the order is delivered : Africa , Europe , LATAM , Pacific Asia , USCA"
25,Order City,: Destination city of the order
26,Order Country,: Destination country of the order
27,Order Customer Id,: Customer order code
28,order date (DateOrders),: Date on which the order is made
29,Order Id,: Order code
30,Order Item Cardprod Id,: Product code generated through the RFID reader
31,Order Item Discount,: Order item discount value
32,Order Item Discount Rate,: Order item discount percentage
33,Order Item Id,: Order item code
34,Order Item Product Price,: Price of products without discount
35,Order Item Profit Ratio,: Order Item Profit Ratio
36,Order Item Quantity,: Number of products per order
37,Sales,: Value in sales
38,Order Item Total,: Total amount per order
39,Order Profit Per Order,: Order Profit Per Order
40,Order Region,": Region of the world where the order is delivered : Southeast Asia ,South Asia ,Oceania ,Eastern Asia, West Asia , West of USA , US Center , West Africa, Central Africa ,North Africa ,Western Europe ,Northern , Caribbean , South America ,East Africa ,Southern Europe , East of USA ,Canada ,Southern Africa , Central Asia , Europe , Central America, Eastern Europe , South of USA"
41,Order State,: State of the region where the order is delivered
42,Order Status,": Order Status : COMPLETE , PENDING , CLOSED , PENDING_PAYMENT ,CANCELED , PROCESSING ,SUSPECTED_FRAUD ,ON_HOLD ,PAYMENT_REVIEW"
43,Product Card Id,: Product code
44,Product Category Id,: Product category code
45,Product Description,: Product Description
46,Product Image,: Link of visit and purchase of the product
47,Product Name,: Product Name
48,Product Price,: Product Price
49,Product Status,": Status of the product stock :If it is 1 not available , 0 the product is available"
50,Shipping date (DateOrders),: Exact date and time of shipment
51,Shipping Mode,": The following shipping modes are presented : Standard Class , First Class , Second Class , Same Day"

In [10]:
len(orders)

180519

In [11]:
orders["Order Id"].nunique()

65752

In [12]:
orders["Order Item Id"].nunique()

180519